apiVersion: apps/v1
kind: Deployment
metadata:
  name: serversample-dep
  labels:
    app: serversample-dep
spec: 
  replicas: 4
  selector:
    matchLabels:
      app: serversample-pod
  minReadySeconds: 5 
  strategy: 
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 1
  template: 
    metadata:
      labels: 
        app: serversample-pod
    spec:
      containers:
        - name: web
          image: registry.cn-shenzhen.aliyuncs.com/gmmy/k8sapisample:oxysvrsmp
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: userservice
spec:
  selector:
    app: serversample-pod
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-dep
  labels:
    app: apigateway-dep
spec: 
  replicas: 4
  selector:
    matchLabels: 
      app: apigateway-pod
  minReadySeconds: 5 
  strategy: 
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 1
  template: 
    metadata:
      labels: 
        app: apigateway-pod
    spec:
      containers:
        - name: web
          image: registry.cn-shenzhen.aliyuncs.com/gmmy/k8sapisample:oxyapiway
          imagePullPolicy: Always 
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: apigateway-svr
spec:
  selector: 
    app: apigateway-pod 
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80 
    nodePort: 30000
  type: NodePort