apiVersion: apps/v1
kind: Deployment
metadata:
  name: serversample-dep
  labels:
    app: serversample-dep
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: serversample-pod
  minReadySeconds: 5 
  strategy: 
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 1
  template: 
    metadata:
      labels: 
        app: serversample-pod
    spec:
      containers:
        - name: web
          image: oxygen-service-sample:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /app
              name: v1
            - mountPath: /remote_debugger:rw
              name: v2
      volumes:
        - name: v1
          hostPath:
            path: /e/dotnet_project/Oxygen/k8s/ServerSample
        - name: v2
          hostPath:
            path: /c/Users/Administrator/vsdbg/vs2017u5
---
apiVersion: v1
kind: Service 
metadata:
  name: serversample
spec:
  selector:
    app: serversample-pod
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-dep
  labels:
    app: apigateway-dep
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: apigateway-pod
  minReadySeconds: 5 
  strategy: 
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 1
  template: 
    metadata:
      labels: 
        app: apigateway-pod
    spec:
      containers:
        - name: web
          image: oxygen-apigateway-sample:latest
          imagePullPolicy: Never 
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /app
              name: v1
            - mountPath: /remote_debugger:rw
              name: v2
      volumes:
        - name: v1
          hostPath:
            path: /e/dotnet_project/Oxygen/k8s/ApiGateWay
        - name: v2
          hostPath:
            path: /c/Users/Administrator/vsdbg/vs2017u5
---
apiVersion: v1
kind: Service 
metadata:
  name: apigateway-svr
spec:
  selector: 
    app: apigateway-pod 
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80 
    nodePort: 30000
  type: NodePort